spring:
  application:
    name: member
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc-member?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123
server:
  port: 8005
  eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
